accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("join-citemed-io/", views.register, name="register"),
    path("login/", views.Login.as_view(), name="login"),
    path("login/abbott/", views.LoginV2.as_view(), name="login_v2"),
    path("logout/", views.LogOut.as_view(), name="logout"),
    path("admin/login/", views.Login.as_view(), name="admin_login"),
    path("admin/logout/", views.LogOut.as_view(), name="admin_logout"),
    path("reset_password/", views.ResetPassword.as_view(), name="reset_password"),
    path("subscription_required/", views.subscription_required, name="subscription_required"),
    path(
        "reset_password_done/",
        views.ResetPasswordDone.as_view(),
        name="reset_password_done",
    ),
    path(
        "reset_password_complete/",
        views.ResetPasswordComplete.as_view(),
        name="reset_password_complete",
    ),
    path(
        "reset_password_confirm/$<uidb64>/<token>/",
        views.ResetPasswordConfirm.as_view(),
        name="reset_password_confirm",
    ),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from apps.tools.constants import API_TOOLS_URL_PREFIX

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('api/auth/', include('apps.auth.urls')),
    path(API_TOOLS_URL_PREFIX, include("apps.tools.urls")),
    path("api/app/", include("apps.app.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
import debug_toolbar
from .views import redirect_view
from .settings import DEBUG, STATIC_URL, STATIC_ROOT
from django.conf.urls import handler404, handler500

urlpatterns = [
    path("", redirect_view),
    path(
        "",
        include("accounts.urls", namespace="accounts"),
    ),
    path(
        "literature_reviews/",
        include("lit_reviews.urls", namespace="literature_reviews"),
    ),
    path(
        "client_portal/",
        include("client_portal.urls", namespace="client_portal"),
    ),
    path(
        "admin_monitoring/",
        include(("admin_side.urls" , "admin_side"), namespace="admin_side"),
    ),
    # path('s3upload/', include('s3upload.urls')),
    path('s3direct/', include('s3direct.urls')),
    path("admin/", admin.site.urls),
] + static(STATIC_URL, document_root=STATIC_ROOT)


if DEBUG:
    urlpatterns.insert(0, path("__debug__/", include(debug_toolbar.urls)))

# error pages
handler404 = 'lit_reviews.views.error_404'
handler500 = 'lit_reviews.views.error_500'
handler403 = 'lit_reviews.views.error_403'

accounts/models.py
from django.db import models 
from django.db.models import Q
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import DO_NOTHING
from datetime import date

from accounts.managers import UserManager


class User(AbstractUser):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username, email and password are required. Other fields are optional.
    """

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    email = models.EmailField(verbose_name="email", max_length=254, unique=True)
    is_ops_member = models.BooleanField(
        "Operations team member",
        default=False,
        help_text="Designates whether the user is a member of our internal CiteMed operations team.",
    )
    is_client = models.BooleanField(
        "client status",
        default=False,
        help_text="Designates whether the user can log into this client site.",
    )
    client = models.ForeignKey(
        "lit_reviews.Client",
        on_delete=DO_NOTHING,
        verbose_name="Main Company",
        related_name="users",
        null=True,
        blank=True,
    )
    companies = models.ManyToManyField(
        "lit_reviews.Client",
        verbose_name="Secondary companies user is part of",
        related_name="all_users",
        null=True,
        blank=True,
    )
    objects = UserManager()

    def __str__(self):
        return self.username
    
    @property
    def my_companies(self):
        "get all user companies user is part of (main and secondary)"
        from client_portal.models import Client

        if self.is_superuser:
            return Client.objects.all()
        elif self.is_ops_member:
            return Client.objects.filter(is_company=False)

        company_ids = list(self.companies.values_list("id", flat=True))
        if self.client and self.client.id:
            company_ids.append(self.client.id)
        return Client.objects.filter(id__in=company_ids)


    def my_reviews(self):
        "Get list of projects (literature reviews) user has access to"
        from lit_reviews.models import LiteratureReview

        if self.is_superuser:
            return LiteratureReview.objects.all()

        companies_review_ids = list(LiteratureReview.objects.filter(client__in=self.my_companies).values_list("id", flat=True))
        external_review_ids = list(LiteratureReview.objects.filter(authorized_users__in=[self]).values_list("id", flat=True))
        all_review_ids_list = [*companies_review_ids, *external_review_ids]

        if self.is_ops_member:
            ops_team_review_ids = list(LiteratureReview.objects.filter(client__is_company=False).values_list("id", flat=True))
            all_review_ids_list = [*all_review_ids_list, *ops_team_review_ids]

        all_review_ids_set = set(all_review_ids_list)
        return LiteratureReview.objects.filter(id__in=all_review_ids_set)


    class Meta:
        db_table = "auth_user"
        verbose_name = "user"
        verbose_name_plural = "users"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    full_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "profile"
        verbose_name_plural = "profiles"


class Subscription(models.Model):
    LICENCE_TYPES = (
        # ('sandbox', 'Sandbox'),
        ('basic', 'Basic'),
        ('credits', 'Credits'),
        ('unlimited', 'Unlimited'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='licence')
    sign_up_date = models.DateTimeField(auto_now_add=True)
    licence_type = models.CharField(max_length=255, choices=LICENCE_TYPES, default='credits')
    licence_start_date = models.DateField(null=True, blank=True)
    licence_end_date = models.DateField(null=True, blank=True)
    stripe_id = models.CharField(max_length=255, null=True, blank=True)

    plan_credits = models.IntegerField(null=True, blank=True)
    remaining_credits = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.licence_type}"

    def days_left(self):
        if not self.licence_start_date or not self.licence_end_date:
            return 0
        
        today = date.today()
        if today >= self.licence_end_date:
            return 0

        return (self.licence_end_date - today).days

    @property
    def is_valid(self):
        if self.licence_type == "unlimited" or self.licence_type == "credits":
            return True 
        elif self.licence_type == "basic" and self.days_left() > 0:
            return True 
        return False 

    class Meta:
        verbose_name = "subscription"
        verbose_name_plural = "subscriptions"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordResetForm,
    SetPasswordForm,
    UserCreationForm
)
from .models import User, Profile

class LogInForm(AuthenticationForm):
    '''LogIn form.'''
    username = forms.CharField(
        label="Username or Email",
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "",
            }
        ),
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                "class": "input",
                "placeholder": "",
            }
        ),
    )

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                "Your sandbox access has ended. Please contact ethan@citemed.io to update your license and restore your account.",
                code="inactive",
            )
        
    def __init__(self, *args, **kwargs):
        super(LogInForm, self).__init__(*args, **kwargs)


class ResetPasswordForm(PasswordResetForm):
    '''Reset password form.'''
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(
            attrs={
                "class": "input",
                "placeholder": "Enter your email",
            }
        ),
    )


class PasswordSetForm(SetPasswordForm):
    '''Password set form.s'''
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter new password",
            }
        ),
    )
    new_password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Confirm new password",
            }
        ),
    )

class UserRegistrationForm(UserCreationForm):
    full_name = forms.CharField(
        label="Full Name",
        max_length=255,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "Enter your full name",
            }
        )
    )
    company_name = forms.CharField(
        label="Company Name",
        max_length=255,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "Enter your company name (optional)",
            }
        )
    )
    phone_number = forms.CharField(
        label="Phone Number",
        max_length=15,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "Enter your phone number (optional)",
            }
        )
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'full_name', 'company_name', 'phone_number']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            profile = Profile.objects.create(
                user=user,
                full_name=self.cleaned_data['full_name'],
                phone_number=self.cleaned_data['phone_number'],
            )
        return user

accounts/views.py
import os 
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy
from .forms import (
    LogInForm,
    ResetPasswordForm,
    PasswordSetForm,
    UserRegistrationForm,
)
from django.shortcuts import render, redirect

from .models import Subscription
from django.conf import settings
from lit_reviews.tasks import send_email

from lit_reviews.models import Client
from django.utils import timezone

from django.contrib.auth import login, authenticate
from backend.logger import logger


def subscription_required(request):
    return render(request, 'accounts/subscription_required.html')

class BaseLogin(LoginView):
    form_class = LogInForm

class Login(BaseLogin):
    template_name = "accounts/login.html"


class LoginV2(BaseLogin):
    template_name = "accounts/login_v2.html"


class LogOut(LogoutView):
    template_name = "accounts/logout.html"


class ResetPassword(PasswordResetView):
    form_class = ResetPasswordForm
    success_url = reverse_lazy("accounts:reset_password_done")
    template_name = "accounts/reset_password.html"
    email_template_name = "accounts/reset_password_email.html"
    subject_template_name = "accounts/reset_password_subject.txt"


class ResetPasswordDone(PasswordResetDoneView):
    template_name = "accounts/reset_password_done.html"


class ResetPasswordConfirm(PasswordResetConfirmView):
    form_class = PasswordSetForm
    success_url = reverse_lazy("accounts:reset_password_complete")
    template_name = "accounts/reset_password_confirm.html"


class ResetPasswordComplete(PasswordResetCompleteView):
    template_name = "accounts/reset_password_complete.html"

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            try:
                user = form.save(commit=False)

                # Collect user info from the form
                full_name = form.cleaned_data.get('full_name')
                company_name = form.cleaned_data.get('company_name')
                phone_number = form.cleaned_data.get('phone_number')

                # create a client
                client_info = company_name if company_name else full_name
                
                # Check if a client with the same name exists
                clients = Client.objects.filter(name=client_info)
                if clients.exists():
                    # Append current time to client_info to make it unique
                    current_time = timezone.now().strftime("%Y%m%d%H%M%S")
                    client_info += f"_{current_time}"

                # Create the client
                client = Client.objects.create(
                    name=client_info,
                    short_name=client_info,
                    long_name=client_info,
                    full_address_string=client_info,
                )
                client.save()

                if client:
                    user.client = client
                    user.is_client = True
                    user.save()

                    # create subscriprion 
                    subscription = Subscription.objects.create(
                        user=user,
                        licence_type='credits',
                        plan_credits=500,
                        remaining_credits=500,
                    )
                    subscription.save()


                    # Send admin email
                    CELERY_DEFAULT_QUEUE = settings.CELERY_DEFAULT_QUEUE
                    subject = "New User Registration in Citemed"
                    message = f"""
                        A new user has registered in Citemed {CELERY_DEFAULT_QUEUE} environment.
                        \n
                        \n Username: {user.username}
                        \n Email: {user.email}
                        \n Full Name: {full_name}
                        \n Company Name: {company_name}
                        \n Phone Number: {phone_number}
                    """
                    SUPPORT_EMAILS = os.getenv("SUPPORT_EMAILS", "").split(",")
                    logger.info(f"sending email notificaiton to: {SUPPORT_EMAILS}")
                    send_email.delay(subject, message, to=SUPPORT_EMAILS)
                    
                    # Authenticate and log in the user
                    raw_password = form.cleaned_data.get('password1')
                    user = authenticate(username=user.username, password=raw_password)
                    if user is not None:
                        login(request, user)                            
                        return redirect("/literature_reviews/")
                    
                    return redirect('accounts:login')
                
                else:
                    form.add_error(None, 'There was an error creating your account. Please try again.')
                    logger.error(f"Error during user registration: {e}")
                    return render(request, 'accounts/register.html', {'form': form})

            except Exception as e:
                form.add_error(None, 'There was an error creating your account. Please try again.')
                logger.error(f"Error during user registration: {e}")
                return render(request, 'accounts/register.html', {'form': form})
        else:
            return render(request, 'accounts/register.html', {'form': form})

    else:
        form = UserRegistrationForm()
    
    return render(request, 'accounts/register.html', {'form': form})

templates/accounts/login.html
{% extends 'base_accounts.html' %}
{% load static %}

{% block head %}
<link href="{% static 'css/base_account.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block title %}<title>Log In</title>{% endblock %}

{% block body %}

<!-- Icon -->
<div class="fadeIn first">
  <div class="account__logo">
  <img
    src="{% static 'images/new_logo.svg' %}"
    id="icon"
    alt="User Icon"
  />
  </div>
</div>

<div>
  <div class="form-header">
    <div class="bold-text">Log in to your account</div>
    <div class="lite-text">Welcome back! Please enter your details.</div>
  </div>
  <form id="form-body" method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}

    <div>
      <div id="login" class="inputText fadeIn">
        {{ form.username.label_tag }}{{ form.username }}
      </div>
      <div id="password" class="inputText fadeIn">
        {{ form.password.label_tag }}{{ form.password }}
      </div>
    </div>
    
    <div class="remember-me">
      <div>        
        <label for="remember_me">
          <input id="remember_me" type="checkbox"/> &#160;
          Remember me 
        </label>
      </div>
      <div>
        <a class="link-text" href="{% url 'accounts:reset_password' %}">Forgot password?</a>
      </div>
    </div>

    <div class="buttons">
      <input type="hidden" name="next" value="{{ next }}" />
      <input type="submit" class="submit-button" value="Sign In" />
    </div>
    {% comment %} <a href="{% url 'accounts:register' %}" class="sing-up-button-section">
      <div type="submit" class="sing-up-button">Create New Account</div>
    </a> {% endcomment %}
  </form>
</div>
{% endblock %}

templates/accounts/login_v2.html
{% extends 'base_accounts.html' %}
{% load static %}

{% block head %}
  <link href="{% static 'css/account_v2.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block title %}<title>Login Page || {% include 'common/sitename.html' %}</title>{% endblock %}

{% block body %}
  <div class="account-container">
    <div class="container-inner-section">
      <div class="form-container">
        <div class="form-header">
          <div class="form-logo">
            <img src="{% static 'images/account/abbott-logo-2.png' %}" class="" />
          </div>
        </div>

        <div class="form-header">
          <div class="form-heading">
            <div class="heading">Sign in</div>
            <div class="subheading">Please login to continue to your account.</div>
          </div>
        </div>
        
        <div class="form-body">
          <form method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <div class="">
              <div id="{{ form.username.id_for_label }}" class="input-wrapper">
                {{ form.username.label_tag }}{{ form.username }}
              </div>
              <div id="{{ form.password.id_for_label }}" class="input-wrapper">
                {{ form.password.label_tag }}{{ form.password }}
              </div>
            </div>
            <div class="remember-me">
              <label for="remember_me">
                <input id="remember_me" type="checkbox" />
                <span class="custom-checkbox"></span>
                &#160; Keep me logged in
              </label>
            </div>          
            <div class="buttons">
              <input type="hidden" name="next" value="{{ next }}" />
              <input type="submit" class="btn btn-primary-500" value="Sign in" />
            </div>
            <div class="divider">
              <span>or</span>
            </div>
            <div class="third-party-buttons">
              <button type="button" class="btn btn-gray-500">Sign in with Salesforce</button>
              <button type="button" class="btn btn-gray-500">Sign in with MS360</button>
            </div>
            <div class="powered-by-logo">
              <img src="{% static 'images/account/powered-by-logo.png' %}" alt="Powered by CiteMed" />
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="container-inner-section">
      <img src="{% static 'images/account/auth.png' %}" width="100%" height="100%" style="object-fit: cover;" class="auth-image" />
    </div>
  </div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base_accounts.html' %}

{% block title %}<title>Log Out</title>{% endblock %}

{% block body %}
<div class="inputText fadeIn second">Logged out!</div>
<div class="buttons">
    <input type="submit" class="submit-button" onclick="window.location='/login/';" value="Log In" />
  </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base_accounts.html' %}
{% load static %}
{% block title %}<title>Register</title>{% endblock %}
{% block head %}
    <link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block body %}
<div>
  <div class="form-header">
    <div class="bold-text">Register a new account</div>
    <div class="lite-text">Please enter your details information.</div>
  </div>
  <form method="post" id="form-body">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-col">
        <div id="username" class="inputText fadeIn">
          {{ form.username.label_tag }}
          {{ form.username }}
        </div>
      </div>
      <div class="form-col">
        <div id="email" class="inputText fadeIn">
          {{ form.email.label_tag }}
          {{ form.email }}
        </div>
      </div>
    </div>
    
    <div class="form-row">
      <div class="form-col">
        <div id="password1" class="inputText fadeIn">
          {{ form.password1.label_tag }}
          {{ form.password1 }}
        </div>
      </div>
      <div class="form-col">
        <div id="password2" class="inputText fadeIn">
          {{ form.password2.label_tag }}
          {{ form.password2 }}
        </div>
      </div>
    </div>
    
    <div class="form-row">
      <div class="form-col">
        <div id="full_name" class="inputText fadeIn">
          {{ form.full_name.label_tag }}
          {{ form.full_name }}
        </div>
      </div>
      <div class="form-col">
        <div id="company_name" class="inputText fadeIn">
          {{ form.company_name.label_tag }}
          {{ form.company_name }}
        </div>
      </div>
    </div>
    
    <div class="form-row">
      <div class="form-col-full">
        <div id="phone_number" class="inputText fadeIn">
          {{ form.phone_number.label_tag }}
          {{ form.phone_number }}
        </div>
      </div>
      <!-- Add more fields in the second column if needed -->
    </div>
    
    {% if form.errors %}
      <div class="badge error mb-2" style="font-size: 14px;">
        {% for errors in form.errors.values %}
          <ul>
            {% for error in errors %}
              <li> {{ error }} </li>
            {% endfor %}
          </ul>
        {% endfor %}
      </div>
    {% endif %}

    <button type="submit" class="submit-button">Register</button>
    <a href="{% url 'accounts:login' %}" class="sing-up-button-section">
      <div type="submit" class="sing-up-button">Sign In</div>
    </a>
  </form>
</div>
{% endblock %}

templates/accounts/reset_password.html
{% extends 'base_accounts.html' %}

{% block title %}<title>Reset password</title>{% endblock %}

{% block body %}

<div>
  <div class="form-header">
    <div class="bold-text">Reset your account</div>
    <div class="lite-text">Please enter your email to reset your password.</div>
  </div>
  <form id="form-body" method="post" action="{% url 'accounts:reset_password' %}">
    {% csrf_token %}

    <div>
      <div id="login" class="inputText fadeIn">
        {{ form.email.label_tag }}{{ form.email }}
      </div>      
    </div>
        
    <div class="reset-pass-button">
      <input type="hidden" name="next" value="{{ next }}" />
      <div>
        <input type="button" onclick="history.back();" class="back-button" value="Back" />
      </div>
      <div>
        <input type="submit" class="submit-button" value="Reset password" />
      </div>
    </div>
  </form>
</div>

{% endblock %}

templates/accounts/reset_password_complete.html
{% extends 'base_accounts.html' %}

{% block title %}<title>Reset password complete</title>{% endblock %}

{% block body %}
<div class="inputText fadeIn second">Password has been changed!</div>
<input type="submit" class="primary-button w-100 mt-2 input fadeIn fourth" onclick="window.location='/login/';" value="Log In" />
{% endblock %}

templates/accounts/reset_password_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}<title>Create new password</title>{% endblock %}

{% block body %}
{% if validlink %}
<form method="post">
  {% csrf_token %}
  <div id="password" class="inputText fadeIn second">{{ form.new_password1.label_tag }}{{ form.new_password1 }}</div>
  <div id="password" class="inputText fadeIn second">{{ form.new_password2.label_tag }}{{ form.new_password2 }}</div>
  <input type="hidden" name="next" value="{{ next }}" />
  <input type="submit" class="primary-button w-100" value="Continue" />
</form>
{% else %}
<div class="inputText fadeIn second">The password reset link was invalid.</div>
<input type="submit" class="secondary-gray-button w-100 mt fadeIn fourth" onclick="window.location='/login/';" value="Log In" />
<input type="button" class="primary-button mt-2 w-100 input fadeIn fourth" onclick="window.location='/reset_password/';" value="Resend" />
{% endif %}
{% endblock %}

templates/accounts/reset_password_done.html
{% extends 'base_accounts.html' %}

{% block title %}<title>Reset password done</title>{% endblock %}

{% block body %}
<div>
    <div class="form-header">
      <div class="bold-text">Reset your account</div>
    </div>
    <div id="form-body">  
        <div>
            <span class="blue-text">
                New password was sent to your E-mail.Please check it!
            </span>
            <br/><br/>
            <span class="blue-text">
                 Don't forget to check your spam as well!
            </span>
        </div>        
      <div class="buttons">
        <input type="hidden" name="next" value="{{ next }}" />
        <input type="submit" onclick="window.location='/login/';" class="submit-button" value="Sign In" />
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:reset_password_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The CiteMedical Team
{% endautoescape %}

templates/accounts/subscription_required.html
{% extends 'base_lit_reviews.html' %}
{% load static %}
{% block 'head' %}
<link href="{% static 'css/error_page.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block 'help_section' %}
<a href="https://citemed-io.gitbook.io/citemed.io-documentation/" target="_blank">
  <span>Need help with this page? <br /> Read the Wiki</span>
  <div>
    <img src="{% static 'images/icons/wiki-icon.svg' %}">
  </div>
</a>
{% endblock %}

{% block 'body' %}
    <div class="body-div" id="error-app">
        <div class="left-div">
            <div class="error-header-section">
                <h1 class="error-code">403</h1>
                <div class="error-title">Access Denied</div>
            </div>
            <div class="error-message-section">
                <div class="error-oops">ooops...</div>
                <div class="error-description">
                    You need an active subscription to continue. You can either purchase a monthy subscription license. Or you can purchase credits based license.
                </div>
            </div>
            <div class="error-btns">
                <a href="https://buy.stripe.com/3cscQG4KH3rD7165ko">
                    <button class="primary-button" >Monthy Subscription</button>
                </a>
                <a href="{{credits_purchase_link}}">
                    <button class="secondary-gray-button" > Credits Licence</button>
                </a> 
            </div>
        </div>
        <div class="right-div">
            <img
                    src="{% static 'images/error-plug.svg' %}"
                    id="icon"
                    alt="Plug Icon"
                    class="plug-error-img"
                    />
        </div>
    </div>
{% endblock %}
{% block 'scripts-block' %}

{% endblock %}