backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from apps.tools.constants import API_TOOLS_URL_PREFIX

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('api/auth/', include('apps.auth.urls')),
    path(API_TOOLS_URL_PREFIX, include("apps.tools.urls")),
    path("api/app/", include("apps.app.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
import debug_toolbar
from .views import redirect_view
from .settings import DEBUG, STATIC_URL, STATIC_ROOT
from django.conf.urls import handler404, handler500

urlpatterns = [
    path("", redirect_view),
    path(
        "",
        include("accounts.urls", namespace="accounts"),
    ),
    path(
        "literature_reviews/",
        include("lit_reviews.urls", namespace="literature_reviews"),
    ),
    path(
        "client_portal/",
        include("client_portal.urls", namespace="client_portal"),
    ),
    path(
        "admin_monitoring/",
        include(("admin_side.urls" , "admin_side"), namespace="admin_side"),
    ),
    # path('s3upload/', include('s3upload.urls')),
    path('s3direct/', include('s3direct.urls')),
    path("admin/", admin.site.urls),
] + static(STATIC_URL, document_root=STATIC_ROOT)


if DEBUG:
    urlpatterns.insert(0, path("__debug__/", include(debug_toolbar.urls)))

# error pages
handler404 = 'lit_reviews.views.error_404'
handler500 = 'lit_reviews.views.error_500'
handler403 = 'lit_reviews.views.error_403'

lit_reviews/api/urls.py
from django.urls import path

from lit_reviews.api.search_terms import  views as SEARCH_TERMS
from lit_reviews.api.adverse_events import views as AE_VIEWS 
from lit_reviews.api.search_dash import views as SEARCH_DASH
from lit_reviews.api.report_builder import views as REPORT_BUILDER
from lit_reviews.api.keywords import views as KEYWORDS
from lit_reviews.api.extraction_fields import views as EXTRACTIONS
from lit_reviews.api.articles import views as ARTICLES
from lit_reviews.api.tags import views as TAGS
from lit_reviews.api.configs import views as PROJECT_CONFIG
from lit_reviews.api.literature_review import views as LIT_REVIEW
from lit_reviews.api.search_protocol import views as SEARCH_PROTOCOL
from lit_reviews.api.home import views as HOME
from lit_reviews.api.clinical_appraisals import views as CLINICAL_APPRAISALS
from lit_reviews.api.actions import views as ACTIONS
from lit_reviews.api.search_notebook import views as SEARCH_NOTEBOOK
from lit_reviews.api.living_reviews import views as  LIVING_REVIEW

urlpatterns = [

    ######################################
    ############## HOME ##################
    ######################################
    
    path("", HOME.LiteratureReviewListAPIView.as_view(), name="literature_review_list_api"),
    path("analysis/", HOME.LiteratureReviewAnalysisView.as_view(), name="literature_review_analysis_api"),
    path("configs/", HOME.CustomerSettingsAPIView.as_view(), name="customer_settings_api"),
    path("configs/<int:settings_id>/", HOME.UpdateCustomerSettingsAPIView.as_view(), name="update_customer_settings_api"),
    path('<int:id>/prisma-data/', HOME.PrismaANDUserDataAPIView.as_view(), name='prisma_data_api_data'),
    path('custom-label/', HOME.CustomLabelAPIView.as_view(), name='custom_label_api'),
    path("custom-label/<int:custom_label_id>/delete/", HOME.DestroySearchLabelOptionView.as_view(), name="custom_label_option"),
    path('support-tickets/', HOME.SupportTicketCreateAPIView.as_view(), name='support_ticket_create_api'),
     

    ######################################
    ########## ADVERSE EVENTS ############
    ######################################

    path("<int:id>/manual_ae_searches/", AE_VIEWS.ManualAdverEventSearchsView.as_view(), name="manual_ae_searches_api"),
    # DELETE
    path("<int:id>/adverse_events/<int:ae_id>/delete/", AE_VIEWS.DestroyAdverseEventReviewView.as_view(), name="ae_destroy"),
    path("<int:id>/adverse_recalls/<int:ae_id>/delete/", AE_VIEWS.DestroyAdverseRecallReviewView.as_view(), name="recall_destroy"),
    # UPDATE 
    path("<int:id>/adverse_events/<int:ae_id>/update/", AE_VIEWS.UpdateAdverseEventReviewView.as_view(), name="ae_update"),
    path("<int:id>/adverse_recalls/<int:ae_id>/update/", AE_VIEWS.UpdateAdverseRecallReviewView.as_view(), name="recall_update"),

    ######################################
    ############## keywords ###############
    ######################################

    path("<int:id>/keyword_api/", KEYWORDS.KeywordView.as_view(), name="keyword_api"),
    path("<int:id>/keyword_api/<int:custom_kw_id>/delete/", KEYWORDS.CustomKeyword.as_view(), name="custom_kw"),
    
    ######################################
    ######### SEARCH TERMS ###############
    ######################################

    path("<int:id>/search_terms/", SEARCH_TERMS.SearchTermsView.as_view(), name="search_terms_api"),
    path("<int:id>/search_terms/validator/", SEARCH_TERMS.SearchTermValidatorView.as_view(), name="search_terms_validator_api"),
    path("<int:id>/search_terms/update/", SEARCH_TERMS.UpdateSearchTermsView.as_view(), name="search_terms_update_api"),
    path("<int:id>/search_terms/result_summary/", SEARCH_TERMS.ResultSummaryView.as_view(), name="result_summary_api"),
    path("<int:id>/search_terms/delete/<int:prop_id>/", SEARCH_TERMS.DeleteSearchTermsView.as_view(), name="search_terms_delete_api"),
    path("<int:id>/search_terms/preview-results/", SEARCH_TERMS.RunPreviewAutoSearchView.as_view(), name="preview_results_api"),
    path("<int:id>/search_terms/preview-status/", SEARCH_TERMS.CheckPreviewStatusAPI.as_view(), name="preview_status_api"),
    path("<int:id>/search_terms/bulk_delete/", SEARCH_TERMS.BulkSearchTermDelteView.as_view(), name="search_terms_bulk_delete_api"),
    
    ######################################
    ######### SEARCH DASHBOARD ###########
    ######################################

    path("<int:id>/search_dashboard/", SEARCH_DASH.SearechDashboardView.as_view(), name="search_dashboard_api"),
    path("<int:id>/search_dashboard/check_status/", SEARCH_DASH.CheckRunningStatusView.as_view(), name="check_running_status_api"),
    path("<int:id>/search_dashboard/run_auto_search/", SEARCH_DASH.RunAutoSearchView.as_view(), name="run_auto_search_api"),
    path("<int:id>/search_dashboard/exclude_search/", SEARCH_DASH.ExcludeSearchView.as_view(), name="exclude_search_api"),
    path("<int:id>/search_dashboard/clear_database/", SEARCH_DASH.ClearDatabaseView.as_view(), name="clear_database_api"),
    path("<int:id>/search_dashboard/generate_report/", SEARCH_DASH.GenerateSearchReportView.as_view(), name="generate_report_api"),
    path("<int:id>/search_dashboard/validate_manual_file_search_api/", SEARCH_DASH.ValidateManualFileSearchView.as_view(), name="validate_manual_file_search_api"),
    path("<int:id>/search_dashboard/upload_citations/", SEARCH_DASH.UploadOwnCitationsAPIView.as_view(), name="upload_citations_api"),
    path("<int:id>/search_dashboard/request_help/", SEARCH_DASH.RequestSupportHelp.as_view(), name="request_help_api"),
    path("anonymous_request_help/", SEARCH_DASH.AnonymousRequestSupportHelp.as_view(), name="anonymous_request_help_api"),
    path("<int:id>/search_dashboard/generate-s3-url/", SEARCH_DASH.CreateAWSS3DirectUploadURL.as_view(), name="generate_s3_url"),
    
    ######################################
    ########## Report Builder ############
    ######################################

    path("<int:id>/report_builder/", REPORT_BUILDER.ReportBuilderView.as_view(), name="report_builder_api"),   
    path("<int:id>/report_builder/delete/<int:report_id>/", REPORT_BUILDER.DestroyReportAPIView.as_view(), name="delete_report_api"),
    path("<int:id>/report_builder/report_status/", REPORT_BUILDER.ReportStatusAPIView.as_view(), name="report_status_api"),
    path("<int:id>/report_builder/full_text_zip/", REPORT_BUILDER.GenerateFullTextZipView.as_view(), name="full_text_zip_api"),
    path("<int:id>/report_builder/update_config/<int:config_id>/", REPORT_BUILDER.UpdateFinalReportConfigView.as_view(), name="update_config_api"),
    path("<int:id>/report_builder/update_comment/<int:report_id>/", REPORT_BUILDER.UpdateReportCommentView.as_view(), name="update_comment_api"),

    ######################################
    ######### Extraction Fields ##########
    ######################################
    
    path("<int:id>/extraction_fields/", EXTRACTIONS.ExtractionFieldsView.as_view(), name="extraction_fields_api"),
    path("<int:id>/extraction_fields/delete/", EXTRACTIONS.ExtractionFieldsBulkDeleteView.as_view(), name="extraction_fields_delete_api"),
    ######################################
    ############# Articles ###############
    ######################################

    path("<int:id>/articles_list_api/", ARTICLES.ArticlesAPIView.as_view(), name="articles_list_api"),
    path("<int:id>/articles_add_comment_api/", ARTICLES.ArticlesAddCommentAPIView.as_view(), name="articles_add_comment_api"),
    path("<int:id>/articles_comments_api/<int:review_id>/", ARTICLES.ArticlesCommentsListAPIView.as_view(), name="articles_comments_api"),
    path("<int:id>/exclusion_reasons_list_api/", ARTICLES.ExclusionReasonListView.as_view(), name="exclusion_reasons_list_api"),
    path("<int:id>/article_tags_api/", ARTICLES.ArticleTagsListView.as_view(), name="article_tags_api"),
    path("<int:id>/bulk_state_update/", ARTICLES.BulkUpdateArticleStateView.as_view(), name="bulk_state_update"),
    path("<int:id>/article_review_update/<int:review_id>/", ARTICLES.UpdateArticleReviewAPIView.as_view(), name="article_review_update"),
    path("<int:id>/article_review_history/<int:review_id>/", ARTICLES.ArticleReviewHistoryAPIView.as_view(), name="article_review_history"),
    path("<int:id>/article_matches/", ARTICLES.ArticleMatchesAPIView.as_view(), name="article_matches_api"),
    path("<int:id>/attach_pdf_api/", ARTICLES.AttachPdfAPIView.as_view(), name="attach_pdf_api"),
    path("<int:id>/articles-historical-status-api/", ARTICLES.ArticlesHistoricalStateAPI.as_view(), name="articles-historical-status-api"),

    path("<int:id>/duplicates_articles_list_api/", ARTICLES.DuplicateArticlesListView.as_view(), name="duplicates_articles_list_api"),
    path("<int:id>/potential_duplicates_articles_list_api/", ARTICLES.PotentialDuplicateArticlesListView.as_view(), name="potential_duplicates_articles_list_api"),
    path("<int:id>/article_review_update_duplicate/<int:review_id>/", ARTICLES.MarkArticleAsDuplicateView.as_view(), name="article_review_update_duplicate"),
    path("<int:id>/1st-pass-ai-suggestions/", ARTICLES.GenerateAISuggestionsAPI.as_view(), name="1st-pass-ai-suggestions"),
    path("<int:id>/upload-full-text/", ARTICLES.UploadFullTextPDFView.as_view(), name="upload-full-text"),
    path("<int:id>/clear-full-text/", ARTICLES.ClearFullTextAPI.as_view(), name="clear-full-text"),


    ######################################
    ############### Tags #################
    ######################################

    path("<int:id>/tags/", TAGS.ArticleTagListAPIView.as_view(), name="article_tags_list_api"),
    path("<int:id>/tags/<int:tag_id>/delete/", TAGS.ArticleTagDeleteAPIView.as_view(), name="article_tags_delete_api"),
    path("<int:id>/tags/<int:tag_id>/update/", TAGS.ArticleTagUpdateAPIView.as_view(), name="article_tags_update_api"),
    path("<int:id>/tags/create/", TAGS.ArticleTagCreateAPIView.as_view(), name="article_tags_create_api"),

lit_reviews/urls.py
from django.urls import include, path
import lit_reviews.citeviews.proposalv2_views as citeviews
import lit_reviews.citeviews.full_text_uploader_views as ftviews
import lit_reviews.search_notebook.views as search_notebook_views
import lit_reviews.citeviews.search_dash as search_dash
import lit_reviews.citeviews.report_builder_dash as report_builder_dash
import lit_reviews.citeviews.articles as articles
import lit_reviews.citeviews.documents_library as documents_library
import lit_reviews.citeviews.exclusion_reason as exclusion_reason
import lit_reviews.citeviews.adverse_events as adverse_events
import lit_reviews.citeviews.products as product
import lit_reviews.citeviews.clinical_literature_appraisal as cl_appraisal
import lit_reviews.citeviews.home as home
import lit_reviews.citeviews.keywords as keywords
import lit_reviews.citeviews.search_lit_review as search_lit
import lit_reviews.citeviews.extraction_fields as extraction_fields

from lit_reviews.citeviews.home import (
    literature_reviews_home, 
    literature_reviews_settings,
    citemed_ms_word_extention,
    living_reviews,
    create_living_review,
    living_review_detail
)


app_name = "lit_reviews"
urlpatterns = [
    # --------------- home views urls ---------------
    path("", literature_reviews_home, name="literature_review_list"),
    path("settings/", literature_reviews_settings, name="literature_reviews_settings"),
    path("living_reviews/", living_reviews, name="living_reviews"),
    path("create_living_review/", create_living_review, name="create_living_review"),
    path("living_reviews/<int:id>/", living_review_detail, name="living_review_detail"),
    path("citemed_ms_word_extention/", citemed_ms_word_extention, name="citemed_ms_word_extention"),
    # path("home/", LiteratureReviewListViewVue, name="literature_review_list_vue"),
    path("<int:id>/", home.literature_review_detail, name="literature_review_detail"),
    path("<int:id>/archive_lit_review/", home.archive_lit_review, name="archive_lit_review"),
    path("create_test_project/", home.create_test_project, name="create_test_project"),
    path("documents_library/",documents_library.documents_library_view,name="documents_library" ),

    # path(
    #     "<int:id>/equivalent_device_discussion",
    #     search_lit.equivalent_device_discussion,
    #     name="equivalent_device_discussion",
    # ),
    path(
        "<int:id>/search_protocol",
        search_lit.search_protocol,
        name="search_protocol",
    ),

    # --------------- searchs views urls ---------------
    path("<int:id>/run_search", search_lit.run_search, name="run_search"),

    # --------------- keywords views urls ---------------
    path("<int:id>/keyword", keywords.keyword, name="keyword"),

    # --------------- articles views urls ---------------
    path(
        "<int:id>/article_review/<int:article_id>",
        articles.article_review_detail,
        name="article_review_detail",
    ),
    path(
        "<int:id>/article_state_change",
        articles.article_state_change,
        name="article_state_change",
    ),
    path(
        "<int:id>/articles/",
        articles.article_reviews_list,
        name="article_reviews_list",
    ),
    path(
        "<int:id>/citation_updater/", 
        articles.citation_updater, 
        name="citation_updater"
    ),
    path(
        "<int:id>/article_tags/", 
        articles.article_tags, 
        name="article_tags"
    ),
    path(
        "<int:id>/duplicates_articles/",
        articles.duplicates_articles,
        name="duplicates_list_url",
    ),
    path(
        "<int:id>/review_article_full_text_pdf/<int:review_id>/",
        articles.review_article_full_text_pdf,
        name="review_article_full_text_pdf",
    ),

    # --------------- search_dash views urls ---------------
    path(
        "<int:id>/search_dashboard",
        search_dash.search_dashboard,
        name="search_dashboard",
    ),
    path(
        "<int:id>/search_terms/", citeviews.search_terms, name="search_terms"
    ),
    
    # --------------- ReportBuilder dash urls ---------------
    path(
        "<int:id>/report_builder",
        report_builder_dash.report_builder,
        name="report_builder",
    ),
    path(
        "<int:id>/exclusion_reason/",
        exclusion_reason.exclusion_reason_list_create,
        name="exclusion_reason",
    ),
    path(
        "<int:id>/exclusion_reason/<int:instance_id>/",
        exclusion_reason.exclusion_reason_update,
        name="exclusion_reason_update",
    ),
    path(
        "<int:id>/exclusion_reason/<int:instance_id>/delete/",
        exclusion_reason.exclusion_reason_delete,
        name="exclusion_reason_delete",
    ),

    # --------------- adverse_events urls ---------------
    path("<int:id>/adverse_database_summary/",
        adverse_events.adverse_database_summary,
        name="adverse_database_summary"
    ),
    path("<int:id>/manual_ae_searches/",
        adverse_events.manual_ae_searches,
        name="manual_ae_searches"
    ),
    path("<int:id>/delete_adverse_event/<int:ae_id>/",
        adverse_events.delete_adverse_event,
        name="delete_adverse_event"
    ),
    path("<int:id>/delete_adverse_recall/<int:ar_id>/",
        adverse_events.delete_adverse_recall,
        name="delete_adverse_recall"
    ),
    path("<int:id>/update_adverse_event/<int:ae_id>/",
        adverse_events.update_adverse_event,
        name="update_adverse_event"
    ),
    path("<int:id>/update_adverse_recall/<int:ar_id>/",
        adverse_events.update_adverse_recall,
        name="update_adverse_recall"
    ),
    path(
        "<int:id>/adverse_event_review/<int:ae_id>",
        adverse_events.adverse_event_review_detail,
        name="adverse_event_review_detail",
    ),
    path("<int:id>/adverse_events", adverse_events.ae_list, name="ae_list"),
    path(
        "adverse_event_review_single/",
        adverse_events.include_single_ae_review,
        name="single_ae_review",
    ),

    # --------------- product urls ---------------
    path("<int:id>/product_details", product.product_details, name="product_details"),
    path(
        "create_literaturereview",
        product.create_literaturereview,
        name="create_literaturereview",
    ),
    # --------------- clinical literature appraisals urls ---------------
    path(
        "<int:id>/clinical_literature_appraisals",
        cl_appraisal.clinical_appraisals_list,
        name="clinical_literature_appraisal_list",
    ),
    path(
        "<int:id>/clinical_literature_appraisal/<int:appraisal_id>",
        cl_appraisal.clinical_literature_appraisal,
        name="clinical_literature_appraisal",
    ),
    path('api/', include('lit_reviews.api.urls')),
    
    # --------------- full text uplode urls ---------------
    # path("upload_ft", ftviews.upload_ft, name="upload_ft"),
    path("<int:id>/full_text_upload", ftviews.ft_uploader, name="full_text_upload"),
    # path("<int:id>/full_text_clear/<int:article_review_id>/", ftviews.ft_clear, name="full_text_clear"),
    path(
        "<int:id>/ft_download_all_files",
        ftviews.ft_download_all_files,
        name="ft_download_all_files",
    ),
    path("fulltext_upload_help", ftviews.fulltext_upload_help, name="fulltext_upload_help"),
    # path("<int:id>/pdf_highlighter", ftviews.pdf_highlighter, name="pdf_highlighter"),
    

    # --------------- Extraction Fields urls ---------------
    path("<int:id>/extraction_fields", extraction_fields.home, name="extraction_fields"),


    ######################################
    ########## Search Notebook ##########
    ######################################
    # --------------- Search Notebook urls ---------------
    path("search_notebook/", search_notebook_views.home, name="search_notebook"),

]

templates/lit_reviews/citation_updater.html
{% extends 'base_lit_reviews.html' %}
{% load static %}
{% block 'head' %}
    <link href="{% static 'css/theme/citation_updater.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block 'help_section' %} 
    <a href="https://citemed-io.gitbook.io/citemed.io-documentation/advanced-topics/fixing-missing-citations"
        target="_blank">
        <span>Need help with this page? <br/> Read the Wiki</span>
        <div>
            <img src="{% static 'images/icons/wiki-icon.svg' %}">
        </div>  
    </a>
{% endblock %} 

{% block 'body' %}
<div class="table-caption">
    <h4 class="header">
        <div>
            Citation Updater ({{articles|length}})
            <div class="tooltip" style="padding-left: 10px;">
                <a class="help-button warning"
                href="https://citemed-io.gitbook.io/citemed.io-documentation/advanced-topics/fixing-missing-citations"
                target="_blank">
                <span>What do I do on this page?</span>
            </a>
            <span class="tooltiptext">Need help with this page? <br/> Read the Wiki</span>
        </div>
    </div>
    </h4>
    <table class="custom-table ">
        <thead class="citation-list-table-header">
            <tr>
                <th scope="col" class="table-header-col id-header-col">Article ID</th>
                <th scope="col" class="table-header-col title-col" >Title</th>
                <th scope="col" class="table-header-col id-header-col">Pubmed UID</th>
                <th scope="col" class="table-header-col id-header-col">PMC UID</th>
                <th scope="col" class="table-header-col ">Citation</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr id="article.article_id">
                <td> {{ article.id }} </td>
                <td> {{ article.title }} </td>
                <td> {{article.pubmed_uid }} </td>
                <td> {{article.pmc_uid }} </td>
                <td>
                    <div class="citation-form">
                        <textarea id="{{ article.id }}"></textarea> 
                        <!-- <input name="citation" id="{{ article.id }}" /> </td> --> 
                        <div>
                            {% if is_archived %}
                                <input data-article-id="{{article.id}}" class="primary-button submit-button disabled" value="submit" type="submit"/>
                            {% else %}
                                <input data-article-id="{{article.id}}" class="primary-button submit-button" value="submit" type="submit"/>
                            {% endif %}
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% csrf_token %}
<script type="text/javascript">
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    $('.submit-button').each((index, input_el) => {
        input_el.addEventListener('click', function (e) {
            const articleId = $(this).data("article-id");
            const citationInputValue = document.getElementById(articleId).value;
            const citationValue = citationInputValue ? citationInputValue : "";
            formData = new FormData();
            formData.append('citation', citationValue)
            formData.append('article_id', articleId)

            $.ajax({
                url: "{% url 'literature_reviews:citation_updater' id=literature_review_id %}",
                type: 'POST',
                data: formData,
                contentType: false, // NEEDED, DON'T OMIT THIS (requires jQuery 1.6+)
                processData: false, // NEEDED, DON'T OMIT THIS
                headers: { 'X-CSRFToken': csrftoken },
                success: function () {
                    location.reload();
                },
                error: function(error){
                    alert(error.responseText);
                }
                })
            });
    })

    </script>
{% endblock %}

templates/lit_reviews/exclusion_reason.html
{% extends 'base_lit_reviews.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block 'head' %}
    <link href="{% static 'css/theme/exclusion_reason.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block 'help_section' %} 
    <a href="https://citemed-io.gitbook.io/citemed.io-documentation/protocol-set-up/define-exclusion-reasons"
        target="_blank">
        <span>Need help with this page? <br/> Read the Wiki</span>
        <div>
        <img src="{% static 'images/icons/wiki-icon.svg' %}">
        </div>
    </a>
{% endblock %} 

{% block 'body' %}
  <div id="app">
    <div class="modal" id="new-reason">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-header-icon-wrapper info-icon">
                        <svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M15.8754 12.4995H12.5004M12.5004 12.4995H9.12537M12.5004 12.4995V15.8744M12.5004 12.4995L12.5004 9.12447M21.5 6.87498L21.5 18.125C21.5 19.989 19.989 21.5 18.125 21.5H6.875C5.01104 21.5 3.5 19.989 3.5 18.125V6.87498C3.5 5.01103 5.01104 3.5 6.875 3.5H18.125C19.989 3.5 21.5 5.01103 21.5 6.87498Z" stroke="#014EE9" stroke-width="1.2" stroke-linecap="round"/>
                        </svg>
                    </div>
                    Add New Reason
                </div>
                
                <form method="post" novalidate>
                    {% csrf_token %}
                    <div class="modal-body" >
                        <div class="reason-form">
                            {{ form|crispy }}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="primary-button">
                            <div class="loader" style="display: none;"></div>
                            <span class="content"> Create </span>
                        </button>
                        <button type="button" class="secondary-gray-button ml" v-on:click="hideModal('new-reason')">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="exclusion-reason-list">
        <h2 class="section-header"> 
            Exclusion Reasons 
            <page-wiki-helper wiki-link="https://citemed-io.gitbook.io/citemed.io-documentation/protocol-set-up/define-exclusion-reasons"> </page-wiki-helper>
            <div class="ml-auto center-v" style="justify-content: end;">                  
                <button 
                    class="primary-button" 
                    target-id="new-reason" 
                    v-on:click="showModal('new-reason')"
                    :disabled="isArchived"
                > 
                    Add New Reason
                </button>
            </div>
        </h2>

        <div class="horizantal-devider"> </div>
      
        {% for exclustion_reason in exclustion_reasons %}
      
        <div class="exclusion-reason-item">
            <div> {{ exclustion_reason.reason }} </div>
            <div class="button-actions">
                <a 
                    href="{% url 'literature_reviews:exclusion_reason_update' id=literature_review_id instance_id=exclustion_reason.id %}" 
                    :class="['primary-button', { 'disabled': isArchived }]"
                    v-if="!isArchived"
                > 
                    Edit 
                </a>
                <a 
                    href="{% url 'literature_reviews:exclusion_reason_delete' id=literature_review_id instance_id=exclustion_reason.id %}" 
                    :class="['error-button', { 'disabled': isArchived }]"
                    v-if="!isArchived"
                > 
                    Delete 
                </a>
            </div>
        </div>
      {% endfor %}
    </div>

  </div>

{% endblock %}

{% block 'after-body' %} 
<script type="application/javascript" src="{% static 'lit_reviews/vue/exclusion_reason.js' %}"></script>
{% endblock %}