accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("join-citemed-io/", views.register, name="register"),
    path("login/", views.Login.as_view(), name="login"),
    path("login/abbott/", views.LoginV2.as_view(), name="login_v2"),
    path("logout/", views.LogOut.as_view(), name="logout"),
    path("admin/login/", views.Login.as_view(), name="admin_login"),
    path("admin/logout/", views.LogOut.as_view(), name="admin_logout"),
    path("reset_password/", views.ResetPassword.as_view(), name="reset_password"),
    path("subscription_required/", views.subscription_required, name="subscription_required"),
    path(
        "reset_password_done/",
        views.ResetPasswordDone.as_view(),
        name="reset_password_done",
    ),
    path(
        "reset_password_complete/",
        views.ResetPasswordComplete.as_view(),
        name="reset_password_complete",
    ),
    path(
        "reset_password_confirm/$<uidb64>/<token>/",
        views.ResetPasswordConfirm.as_view(),
        name="reset_password_confirm",
    ),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from apps.tools.constants import API_TOOLS_URL_PREFIX

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('api/auth/', include('apps.auth.urls')),
    path(API_TOOLS_URL_PREFIX, include("apps.tools.urls")),
    path("api/app/", include("apps.app.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
import debug_toolbar
from .views import redirect_view
from .settings import DEBUG, STATIC_URL, STATIC_ROOT
from django.conf.urls import handler404, handler500

urlpatterns = [
    path("", redirect_view),
    path(
        "",
        include("accounts.urls", namespace="accounts"),
    ),
    path(
        "literature_reviews/",
        include("lit_reviews.urls", namespace="literature_reviews"),
    ),
    path(
        "client_portal/",
        include("client_portal.urls", namespace="client_portal"),
    ),
    path(
        "admin_monitoring/",
        include(("admin_side.urls" , "admin_side"), namespace="admin_side"),
    ),
    # path('s3upload/', include('s3upload.urls')),
    path('s3direct/', include('s3direct.urls')),
    path("admin/", admin.site.urls),
] + static(STATIC_URL, document_root=STATIC_ROOT)


if DEBUG:
    urlpatterns.insert(0, path("__debug__/", include(debug_toolbar.urls)))

# error pages
handler404 = 'lit_reviews.views.error_404'
handler500 = 'lit_reviews.views.error_500'
handler403 = 'lit_reviews.views.error_403'

client_portal/api/urls.py
from django.urls import path
from client_portal.api.DocumentsLibrary import views as DocuumentsLibraryViews 
from client_portal.api.projects import views as ProjectsViews 
from client_portal.api.AutomatedSearch import views as AutomatedSearchViews 

urlpatterns = [

    ######################################
    ############## Projects #############
    ######################################
    path("projects/", ProjectsViews.ProjectsListAPIView.as_view(), name="projects_api"),
    path("devices/", ProjectsViews.DeviceListAPIView.as_view(), name="devices_api"),
    path("messages/", ProjectsViews.MessagesListAPIView.as_view(), name="messages_api"),

    ######################################
    ########## Documents Lib #############
    ######################################
    path("documents_library/", DocuumentsLibraryViews.DocumentsLibraryAPIView.as_view(), name="documents_library_api"),
    path("library_entry_filters/", DocuumentsLibraryViews.LibraryEntryFiltersAPI.as_view(), name="library_entry_filters"),
    path("update_article/<int:article_id>/", DocuumentsLibraryViews.UpdateArticleView.as_view(), name="update_article_api"),
    path("documents_library/create_article", DocuumentsLibraryViews.CreateArticleAPIView.as_view(), name="create_article_api"),
    
   
    ######################################
    ########## Automated Search ##########
    ######################################

    path("automated_search/", AutomatedSearchViews.AutomatedSearchAPIView.as_view(), name="automated_search_api"),
    path("create_automated_search/", AutomatedSearchViews.CreateAutomatedSearchAPIView.as_view(), name="create_automated_search_api"),
    path("automated_search_results/<int:search_id>/", AutomatedSearchViews.AutomatedSearchResultsAPIView.as_view(), name="automated_search_results_api"),
    path("automated_search_save_to_library/<int:search_id>/", AutomatedSearchViews.AutomatedSearchSaveToLibraryAPIView.as_view(), name="automated_search_save_to_library_api"),
    path("create_article_comment_api/", AutomatedSearchViews.CreateArticleCommentAPIView.as_view(), name="create_article_comment_api"),
    path("update_automated_search_api/<int:search_id>/", AutomatedSearchViews.UpdateAutomatedSearchAPIView.as_view(), name="update_automated_search_api"),
     
]

client_portal/urls.py
from django.urls import path, include

from .views import (
    client_home,
    documents_library,
    project_details,
    projects_list,
    templates,
    vigilance,
    intake_form,
    actions,
    company_overview,
    event,
    report_overview,
    action_details,
    event_details,
    recall_details,
    article_details,
    automated_search,
    create_automated_search,
    automated_search_results,
    automated_search_update,
    export_automated_search_results,
)


app_name = "client_portal"
urlpatterns = [
    path("", client_home, name="client_home"),
    path("documents_library/", documents_library, name="documents_library"),
    path("project_details/<int:id>/", project_details, name="project_details"),
    path("projects_list/", projects_list, name="projects_list"),
    path("templates/", templates, name="templates"),
    path("vigilance/", vigilance, name="vigilance"),
    path("<int:id>/intake_form/", intake_form, name="intake_form"),
    path("actions/", actions, name="actions"),
    path("action_details/<int:id>", action_details, name="action_details"),
    path("company_overview/", company_overview, name="company_overview"),
    path("event/", event, name="event"),
    path("report_overview/", report_overview, name="report_overview"),
    path("events/<int:id>/details/", event_details, name="event_details"),
    path("recalls/<int:id>/details/", recall_details, name="recall_details"),
    path("articles/<int:id>/details/", article_details, name="article_details"),
    path("automated_search/", automated_search, name="automated_search"),
    path("create_automated_search/", create_automated_search, name="create_automated_search"),
    path("automated_search/<int:id>/", automated_search_update, name="automated_search_update"),
    path("automated_search_results/<int:id>/", automated_search_results, name="automated_search_results"),
    path("export_automated_search_results/<int:id>/", export_automated_search_results, name="export_automated_search_results"),
    

    path("api/", include("client_portal.api.urls")),
]

client_portal/forms.py
from django.forms import forms
from .models import (
    Project,
    Action,
    Deliverable,
)


class IntakeFormLiteratureReview:
    ...


class IntakeFormCER:
    ...


class IntakeFormPMS:
    ...

client_portal/api/AutomatedSearch/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from django.core.paginator import Paginator
import json
from django.db.models import Q
from django.utils import timezone
from django.shortcuts import get_object_or_404

from client_portal.tasks import create_terms_for_automated_searches_initial
from client_portal.models import (
    AutomatedSearchProject,
    ArticleComment,
    LibraryEntry,
)
from lit_reviews.models import (
    Device,
    Manufacturer,
    NCBIDatabase,
    LiteratureReview,
    Article,
    LiteratureSearch,
    LiteratureReviewSearchProposal,
    ArticleReview,
    Client,
)

from client_portal.api.AutomatedSearch.serializers import (
    AutomatedSearchProjectSerializer,
    DeviceSerializer,
    ManufacturerSerializer,
    NCBIDatabaseSerializer,
    ArticleSerializer,
    DateRangesFilterValuesSerailizer,
    ArticleReviewSerializer,
    ClientSerailizer,
)



from client_portal.api.permissions import isClient, isArticleOwner


class AutomatedSearchAPIView(APIView):
    permission_classes = [IsAuthenticated,]

    def get(self, request, *args, **kwargs):    
        if request.user.client:    
            automated_search_projects = AutomatedSearchProject.objects.filter(client=request.user.client).order_by("-id")
        else:
            automated_search_projects = AutomatedSearchProject.objects.all().order_by("-id")

        serializer = AutomatedSearchProjectSerializer(automated_search_projects,many=True)
        return Response({
            "entries": serializer.data,
        }, status=status.HTTP_200_OK)


class CreateAutomatedSearchAPIView(APIView):
    permission_classes = [IsAuthenticated,]

    def get(self, request, *args, **kwargs):   
        if request.user.client:  
            lit_reviews = LiteratureReview.objects.filter(client=request.user.client)
            clients_list = []
        else:
            lit_reviews = LiteratureReview.objects.all()
            clients = Client.objects.all()
            clients_ser = ClientSerailizer(clients, many=True)
            clients_list = clients_ser.data
            
        devices = Device.objects.filter(literaturereview__in=lit_reviews).distinct()
        devices_ser = DeviceSerializer(devices, many=True)

        manufacturers = Manufacturer.objects.filter(device__in=devices).distinct()
        manufacturers_ser = ManufacturerSerializer(manufacturers, many=True)

        not_isrecall = Q( Q(is_recall=None) | Q(is_recall=False) )
        not_isae = Q( Q(is_ae=None) | Q(is_ae=False) )
        not_recall_and_not_ae = Q( not_isrecall & not_isae)
        isrecall_or_isae = Q( Q(is_ae=True) | Q(is_recall=True) )


        lit_dbs = NCBIDatabase.objects.filter(not_recall_and_not_ae, is_archived=False)
        
        ae_databases = NCBIDatabase.objects.filter(isrecall_or_isae, is_archived=False)
        ae_basic_dbs = []
        ae_extra_dbs = []
        
        for ae_database in ae_databases:
            if ae_database.entrez_enum == "maude_recalls" or ae_database.entrez_enum == "embase" or ae_database.entrez_enum == "scholar":
                ae_basic_dbs.append(ae_database)
            else:
                ae_extra_dbs.append(ae_database)


        lit_dbs_ser = NCBIDatabaseSerializer(lit_dbs, many=True)
        ae_basic_dbs_ser = NCBIDatabaseSerializer(ae_basic_dbs, many=True)
        ae_extra_dbs_ser = NCBIDatabaseSerializer(ae_extra_dbs, many=True)


        return Response({
                "devices": devices_ser.data,
                "manufacturers": manufacturers_ser.data,
                "lit_dbs": lit_dbs_ser.data,
                "ae_basic_dbs": ae_basic_dbs_ser.data,
                "ae_extra_dbs": ae_extra_dbs_ser.data,
                "clients": clients_list,
            }, 
            status=status.HTTP_200_OK
        )
    
    def post(self, request, *args, **kwargs):
        # Extract data from the POST request
        automation_data = request.data

        create_device = automation_data["createDevice"]
        create_manufacturer = automation_data["createManufacturer"]
        device_name = automation_data["deviceName"]
        manufacturer_name = automation_data["manufacturerName"]
        manufacturer = automation_data["selectedManufacturer"]
        classification = automation_data["classification"]
        markets = automation_data["markets"]
        selected_device = automation_data["selectedDevice"]
        selected_interval = automation_data["selectedInterval"]
        selected_dbs_json = request.POST.get('selectedDbs')
        selected_dbs = json.loads(selected_dbs_json)
        search_type = automation_data["searchType"]
        search_term = automation_data["searchTerms"]
        search_file = automation_data["searchFile"]
        start_date = automation_data["startDate"]
        selected_client = automation_data["client"]

        if create_device == "true":
            # Your logic for creating a device
            if create_manufacturer == "true":
                manufacturer = Manufacturer.objects.create(name=manufacturer_name)
                manufacturer.save()
            else:
                manufacturer = get_object_or_404(Manufacturer, name=manufacturer)

            device = Device.objects.create(
                name = device_name,
                manufacturer = manufacturer,
                classification=classification,
                markets=markets
            )
            device.save()
        else:
            device = Device.objects.filter(id = selected_device).first()

        if request.user.client:
            client = request.user.client
        else:
            client = get_object_or_404(Client, id=selected_client)

        # create lit_review
        __filters = {
            "client": client,
            "device": device,
            "is_autosearch": True,
        }
        lit_review = LiteratureReview.objects.filter(**__filters).first()
        if not lit_review:
            lit_review = LiteratureReview.objects.create(**__filters)
            lit_review.save()
            lit_review.authorized_users.add(request.user)

        automated_search_project = AutomatedSearchProject.objects.create(
            lit_review = lit_review,
            client = client,
            interval = selected_interval,
            start_date = start_date,
        )
        automated_search_project.save()

        if search_type == 'terms':
            automated_search_project.terms = search_term
            create_terms_for_automated_searches_initial.delay(
                selected_dbs, 
                search_term, 
                lit_review.id, 
                start_date, 
                selected_interval, 
                str(automated_search_project.client),
                automated_search_project.id,
            )

        else:
            automated_search_project.terms_file = search_file
        automated_search_project.save()


        for db in selected_dbs:
            db_item = NCBIDatabase.objects.filter(displayed_name = db).first()
            automated_search_project.databases_to_search.add(db_item)
            protocol = lit_review.searchprotocol
            if db_item.is_ae or db_item.is_recall:
                protocol.ae_databases_to_search.add(db_item)
            else:
                protocol.lit_searches_databases_to_search.add(db_item)
            
            protocol.lit_date_of_search = start_date
            protocol.ae_date_of_search = start_date
            protocol.save()

        return Response({
            "message": "Automated Search Project Created Successfully"
        }, status=status.HTTP_200_OK)
        



class AutomatedSearchResultsAPIView(APIView):
    permission_classes = [IsAuthenticated, ]

    def get(self, request, *args, **kwargs):        
        search_id = self.kwargs.get('search_id')
        date_filter = self.request.query_params.get("date_filter")
        automated_search = AutomatedSearchProject.objects.filter(id = search_id).first()

        article_reviews = ArticleReview.objects.filter(
            search__literature_review=automated_search.lit_review,
            search__term=automated_search.terms,
        ).exclude(state="D")
        lit_searches = LiteratureSearch.objects.filter(
            literature_review=automated_search.lit_review,
            term=automated_search.terms,
        )
        
        completed_searches = [search for search in lit_searches if search.is_completed] 
        did_search_fail = lit_searches.filter(import_status="INCOMPLETE-ERROR").count() > 0
        is_search_completed =  len(completed_searches) == lit_searches.count()
        
        search_status = "Pending" 
        if did_search_fail: 
            search_status = "Failed"
        elif is_search_completed:
            search_status = "Completed"

        ranges_dates_distinct = lit_searches.distinct("start_search_interval").values(
            "start_search_interval", "end_search_interval"
        )
        ranges_dates_distinct = [
            {
                "id": date["start_search_interval"].strftime("%d-%m-%Y"), 
                "value": "{} to {}".format(
                    date["start_search_interval"].strftime("%d-%m-%Y"), 
                    date["end_search_interval"].strftime("%d-%m-%Y")
                )
            } 
            for date in ranges_dates_distinct
        ]
        dates_filter_values_ser = DateRangesFilterValuesSerailizer(ranges_dates_distinct, many=True)

        if date_filter:
            date_filter = timezone.datetime.strptime(date_filter, "%d-%m-%Y")
            article_reviews = article_reviews.filter(search__start_search_interval=date_filter)
            lit_searches = lit_searches.filter(start_search_interval=date_filter)
            
            completed_searches = [search for search in lit_searches if search.is_completed] 

templates/client_portal/client_home.html
{% extends "base_client_portal.html" %}
{% load static %}

{% block title%}
    <title>CiteMed - Dashboard</title>
{% endblock %}

{% block head %}{% endblock %}

{% block body %}
    <div class="content__container" id="content">
        <div class="sub-navbar-home">
            <div class="sub-navbar-home-item-text">
                Dashboard
            </div>
            <div :class="active_tab === 'messages' ? 'sub-navbar-home-item-active' : 'sub-navbar-home-item-inactive'" id="messages-tab" v-on:click="changeselectedtab('messages')">
                Messages  and Alerts
            </div>
            <div :class="active_tab === 'projects' ? 'sub-navbar-home-item-active' : 'sub-navbar-home-item-inactive'" id="projects-tab" v-on:click="changeselectedtab('projects')">
                Projects
            </div>
            <div :class="active_tab === 'vigilance' ? 'sub-navbar-home-item-active' : 'sub-navbar-home-item-inactive'" id="vigilance-tab" v-on:click="changeselectedtab('vigilance')">
                Vigilance Data
            </div>
        </div>
        <div :class="active_tab === 'messages' ? 'home-section-item-selected' : 'home-section-item-unselected'" id="messages-section">
            <div class="">
                <div v-if="isRecordsLoading"> Loading... </div>
                <div v-else-if="messages">
                    <div class="project-table-header">
                        <div class="message-table-header message-table-type">Type</div>
                        <div class="message-table-header message-table-date">Date Sent</div>
                        <div class="message-table-header message-table-project">Project Id</div>
                        <div class="message-table-header message-table-message">Message</div>
                        <div class="message-table-header message-table-status"> Status </div>
                        <div class="message-table-header message-table-details"> Full Details </div>
                    </div>
                    <div class="project-table-body">
                        <div v-for="message in messages" class="project-table-body-item">
                            <div class="message-table-body message-table-type"> [[ message.type ]] </div>
                            <div class="message-table-body message-table-date"> [[ message.date_sent]] </div>
                            <div class="message-table-body message-table-project"> # [[ message.project ]] </div>
                            <div class="message-table-body message-table-message"> [[ message.message ]] </div>
                            <div class="message-table-body message-table-status"> 
                                <div :class="message.resolved_status === 'read' ? 'message-status-read' : message.resolved_status === 'unread' ? 'message-status-unread' : 'message-status-hidden'">
                                    [[ message.resolved_status ]] 
                                </div>
                            </div>
                            <div class="message-table-body message-table-details">
                                <a class="project-table-body-action-link" :href="[[ message.detail_view_hyperlink ]]"> 
                                    <img
                                    src="{% static 'images/icons/plus-detail-icon.svg' %}"
                                    alt=""
                                    class="project-table-body-action-icon"
                                    />   
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="no-project-text" v-else>No data.</div>
            </div>
        </div>
        <div :class="active_tab === 'projects' ? 'home-section-item-selected' : 'home-section-item-unselected'" id="projects-section">
            <div class="project-filter-navbar">
                <div class="input-group search_filter search-project-name-section">
                    <input type="text" class="form-control search-project-name-section-input" placeholder="Search by Project Name" v-model="search_term">
                    <div class="input-group-append  search-project-name-section-input-submit">
                    <button class="btn search-btn" type="button" v-on:click="onFilter">
                        <span class="fa fa-search"></span>
                    </button>
                    </div>
                </div>
                <div class="project-filter-navbar-type" style="margin-left:25px">
                    <select v-on:change="onTypeFilterChange" name="" id="project-filter-navbar-type-select" class="project-filter-navbar-type-select">
                        <option value="" :selected="typeFilter===''"> Select Project Type </option>
                        <option v-for="type in types" :value="type.id" :selected="typeFilter===type.id"> [[ type.name ]] </option>
                    </select>
                </div>
                <div class="project-filter-navbar-date">
                    <!-- <input type="date" name="" id="project-filter-navbar-date-input" class="project-filter-navbar-date-input"> -->
                    <div class="project-filter-navbar-date-text"> Date: </div>
                    <vuejs-datepicker 
                        format="yyyy-MM-dd"
                        v-model="dateFilter"         
                        name="datepicker"
                        id="input-id"
                        input-class="project-filter-navbar-date-input"
                        >
                    </vuejs-datepicker>
                </div>
                <div class="project-filter-navbar-submit">
                    <button class="project-filter-navbar-submit-btn" v-on:click="onClearFilters" > Clear Filters </button>
                </div>
            </div>
            <div class="">
                <div v-if="isRecordsLoading"> Loading... </div>
                <div v-else-if="projects">
                    <div class="project-table-header">
                        <div class="project-table-header-name">Project Name</div>
                        <div class="project-table-header-date">Date</div>
                        <div class="project-table-header-type">Type</div>
                        <div class="project-table-header-action"> Full Detail </div>
                    </div>
                    <div class="project-table-body">
                        <div v-for="project in projects" class="project-table-body-item">
                            <div class="project-table-body-name"> [[ project.name ]] </div>
                            <div class="project-table-body-date"> [[ project.initial_complated_date ? project.initial_complated_date : "N/A"]] </div>
                            <div class="project-table-body-type"> [[ project.type ]] </div>
                            <div class="project-table-body-action">
                                <a class="project-table-body-action-link" :href="[[ project.detail_view_hyperlink ]]"> 
                                    <img
                                    src="{% static 'images/icons/plus-detail-icon.svg' %}"
                                    alt=""
                                    class="project-table-body-action-icon"
                                    />   
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="no-project-text" v-else>No data.</div>
            </div>

        </div>
        <div :class="active_tab === 'vigilance' ? 'home-section-item-selected' : 'home-section-item-unselected'" id="vigilance-section">
            <div class="no-project-text">No data.</div>
        </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js" integrity="sha512-odNmoc1XJy5x1TMVMdC7EMs3IVdItLPlCeL5vSUPN2llYKMJ2eByTTAIiiuqLg+GdNr9hF6z81p27DArRFKT7A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script>
        const projectsURL = "{% url 'client_portal:projects_api' %}";
        const messagesURL = "{% url 'client_portal:messages_api' %}";
    </script>
    
    {% if env == 'PROD' %}
    <script type="application/javascript" src="https://cdn.jsdelivr.net/npm/vue@2.7.0"></script>
    {% else %}
    <script type="application/javascript" src="https://cdn.jsdelivr.net/npm/vue@2.7.0/dist/vue.js"></script>
    {% endif %}

    <script src="{% static 'vue-cdn/propper-2.11.8.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/portal-vue@2.1.7/dist/portal-vue.umd.min.js"></script>
    <script src="{% static 'vue-cdn/bootstrap-vue-2.23.1.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vuejs-datepicker/1.6.2/vuejs-datepicker.min.js" integrity="sha512-SxUBqfNhPSntua7WUkt171HWx4SV4xoRm14vLNsdDR/kQiMn8iMUeopr8VahPpuvRjQKeOiMJTJFH5NHzNUHYQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'client_portal/vue/dashboard.js' %}" > </script>

{% endblock %}

templates/client_portal/company_overview.html
{% extends "base_client_portal.html" %}
{% load static %}
{% block title%}
    <title>CiteMed - Company</title>
{% endblock %}

{% block head %}{% endblock %}

{% block body %}
<div class="content__container" id="content">
    <div class="sub-navbar-home">
        <div class="sub-navbar-home-item-text">
            Company Overview
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/client_portal/deliverable_create_email.html
{% autoescape off %}
Dear {{ email.username }}.
New delivery was created:

project: {{deliverable.project}}
file: {{deliverable.file}}
version_short_name: {{deliverable.version_short_name}}
previous: {{deliverable.previos}}
date: {{deliverable.date}}
comments: {{deliverable.comments}}
comments_revision_file: {{deliverable.comments_revision_file}}
status: {{deliverable.status}}


Sincerely,
The CiteMedical Team
{% endautoescape %}

templates/client_portal/sidebar.html
<div class="sidebar__container" id="sidebar">
    {% load static %}
    {% block head %}
    <link href="{% static 'css/sidebar.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/client_portal/sidebar.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'js/sidebar.js' %}"></script>
    {% endblock %}
    <div class="sidebar__logo">
        <img
          src="{% static 'images/new_logo.svg' %}"
          alt=""
        />
    </div>
    <!-- Dashboard -->
    <a href="{% url 'client_portal:client_home' %}" class="sidebar-item">
        <img
            src="{% static 'images/icons/dashboard-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Dashboard</span>
    </a>
    <!-- Vigilance -->
    <a href="{% url 'client_portal:vigilance' %}?filter_status=I,IN" class="sidebar-item">
        <img
            src="{% static 'images/icons/vigilance-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Vigilance</span>
    </a>
    <!-- Templates -->
    <a href="{% url 'client_portal:templates' %}" class="sidebar-item">
        <img
            src="{% static 'images/icons/templates-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Templates</span>
    </a>
    <!-- Documents -->
    <a href="{% url 'client_portal:documents_library' %}" class="sidebar-item">
        <img
            src="{% static 'images/icons/documents-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Documents</span>
    </a>
    <!-- Projects -->
    <a href="{% url 'client_portal:projects_list' %}" class="sidebar-item">
        <img
            src="{% static 'images/icons/projects-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Projects</span>
    </a>
    <!-- Automated Search -->
    <a href="{% url 'client_portal:automated_search' %}" class="sidebar-item">
        <img
            src="{% static 'images/icons/automated-search-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Automated Search</span>
    </a>
    <!-- Events -->
    <a href="{% url 'client_portal:event' %}" class="sidebar-item">
        <img
            src="{% static 'images/icons/events-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Events</span>
    </a>
    <!-- Company -->
    <a href="{% url 'client_portal:company_overview' %}" class="sidebar-item">
        <img
            src="{% static 'images/icons/company-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Company</span>
    </a>
    <!-- Report -->
    <a href="{% url 'client_portal:report_overview' %}" class="sidebar-item">
        <img
            src="{% static 'images/icons/report-icon.svg' %}"
            alt=""
            class="sidebar-item-icon"
        />
        <span class="sidebar-item-text">Report</span>
    </a>    
</div>