accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("join-citemed-io/", views.register, name="register"),
    path("login/", views.Login.as_view(), name="login"),
    path("login/abbott/", views.LoginV2.as_view(), name="login_v2"),
    path("logout/", views.LogOut.as_view(), name="logout"),
    path("admin/login/", views.Login.as_view(), name="admin_login"),
    path("admin/logout/", views.LogOut.as_view(), name="admin_logout"),
    path("reset_password/", views.ResetPassword.as_view(), name="reset_password"),
    path("subscription_required/", views.subscription_required, name="subscription_required"),
    path(
        "reset_password_done/",
        views.ResetPasswordDone.as_view(),
        name="reset_password_done",
    ),
    path(
        "reset_password_complete/",
        views.ResetPasswordComplete.as_view(),
        name="reset_password_complete",
    ),
    path(
        "reset_password_confirm/$<uidb64>/<token>/",
        views.ResetPasswordConfirm.as_view(),
        name="reset_password_confirm",
    ),
]

admin_side/api/urls.py
from django.urls import path
import admin_side.api.scraper_monitor.views as SCRAPER_MONITOR

urlpatterns = [
    path("scraper_reports/", SCRAPER_MONITOR.ScraperReportsListAPIView.as_view(), name="scraper-report-api-list"),
] 

admin_side/urls.py
from django.urls import path, include
from .views import home

urlpatterns = [
    path("", home, name="admin-side-home"),
    path(
        "api/",
        include("admin_side.api.urls"),
    ),
] 

backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from apps.tools.constants import API_TOOLS_URL_PREFIX

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('api/auth/', include('apps.auth.urls')),
    path(API_TOOLS_URL_PREFIX, include("apps.tools.urls")),
    path("api/app/", include("apps.app.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
import debug_toolbar
from .views import redirect_view
from .settings import DEBUG, STATIC_URL, STATIC_ROOT
from django.conf.urls import handler404, handler500

urlpatterns = [
    path("", redirect_view),
    path(
        "",
        include("accounts.urls", namespace="accounts"),
    ),
    path(
        "literature_reviews/",
        include("lit_reviews.urls", namespace="literature_reviews"),
    ),
    path(
        "client_portal/",
        include("client_portal.urls", namespace="client_portal"),
    ),
    path(
        "admin_monitoring/",
        include(("admin_side.urls" , "admin_side"), namespace="admin_side"),
    ),
    # path('s3upload/', include('s3upload.urls')),
    path('s3direct/', include('s3direct.urls')),
    path("admin/", admin.site.urls),
] + static(STATIC_URL, document_root=STATIC_ROOT)


if DEBUG:
    urlpatterns.insert(0, path("__debug__/", include(debug_toolbar.urls)))

# error pages
handler404 = 'lit_reviews.views.error_404'
handler500 = 'lit_reviews.views.error_500'
handler403 = 'lit_reviews.views.error_403'

client_portal/urls.py
from django.urls import path, include

from .views import (
    client_home,
    documents_library,
    project_details,
    projects_list,
    templates,
    vigilance,
    intake_form,
    actions,
    company_overview,
    event,
    report_overview,
    action_details,
    event_details,
    recall_details,
    article_details,
    automated_search,
    create_automated_search,
    automated_search_results,
    automated_search_update,
    export_automated_search_results,
)


app_name = "client_portal"
urlpatterns = [
    path("", client_home, name="client_home"),
    path("documents_library/", documents_library, name="documents_library"),
    path("project_details/<int:id>/", project_details, name="project_details"),
    path("projects_list/", projects_list, name="projects_list"),
    path("templates/", templates, name="templates"),
    path("vigilance/", vigilance, name="vigilance"),
    path("<int:id>/intake_form/", intake_form, name="intake_form"),
    path("actions/", actions, name="actions"),
    path("action_details/<int:id>", action_details, name="action_details"),
    path("company_overview/", company_overview, name="company_overview"),
    path("event/", event, name="event"),
    path("report_overview/", report_overview, name="report_overview"),
    path("events/<int:id>/details/", event_details, name="event_details"),
    path("recalls/<int:id>/details/", recall_details, name="recall_details"),
    path("articles/<int:id>/details/", article_details, name="article_details"),
    path("automated_search/", automated_search, name="automated_search"),
    path("create_automated_search/", create_automated_search, name="create_automated_search"),
    path("automated_search/<int:id>/", automated_search_update, name="automated_search_update"),
    path("automated_search_results/<int:id>/", automated_search_results, name="automated_search_results"),
    path("export_automated_search_results/<int:id>/", export_automated_search_results, name="export_automated_search_results"),
    

    path("api/", include("client_portal.api.urls")),
]

lit_reviews/urls.py
from django.urls import include, path
import lit_reviews.citeviews.proposalv2_views as citeviews
import lit_reviews.citeviews.full_text_uploader_views as ftviews
import lit_reviews.search_notebook.views as search_notebook_views
import lit_reviews.citeviews.search_dash as search_dash
import lit_reviews.citeviews.report_builder_dash as report_builder_dash
import lit_reviews.citeviews.articles as articles
import lit_reviews.citeviews.documents_library as documents_library
import lit_reviews.citeviews.exclusion_reason as exclusion_reason
import lit_reviews.citeviews.adverse_events as adverse_events
import lit_reviews.citeviews.products as product
import lit_reviews.citeviews.clinical_literature_appraisal as cl_appraisal
import lit_reviews.citeviews.home as home
import lit_reviews.citeviews.keywords as keywords
import lit_reviews.citeviews.search_lit_review as search_lit
import lit_reviews.citeviews.extraction_fields as extraction_fields

from lit_reviews.citeviews.home import (
    literature_reviews_home, 
    literature_reviews_settings,
    citemed_ms_word_extention,
    living_reviews,
    create_living_review,
    living_review_detail
)


app_name = "lit_reviews"
urlpatterns = [
    # --------------- home views urls ---------------
    path("", literature_reviews_home, name="literature_review_list"),
    path("settings/", literature_reviews_settings, name="literature_reviews_settings"),
    path("living_reviews/", living_reviews, name="living_reviews"),
    path("create_living_review/", create_living_review, name="create_living_review"),
    path("living_reviews/<int:id>/", living_review_detail, name="living_review_detail"),
    path("citemed_ms_word_extention/", citemed_ms_word_extention, name="citemed_ms_word_extention"),
    # path("home/", LiteratureReviewListViewVue, name="literature_review_list_vue"),
    path("<int:id>/", home.literature_review_detail, name="literature_review_detail"),
    path("<int:id>/archive_lit_review/", home.archive_lit_review, name="archive_lit_review"),
    path("create_test_project/", home.create_test_project, name="create_test_project"),
    path("documents_library/",documents_library.documents_library_view,name="documents_library" ),

    # path(
    #     "<int:id>/equivalent_device_discussion",
    #     search_lit.equivalent_device_discussion,
    #     name="equivalent_device_discussion",
    # ),
    path(
        "<int:id>/search_protocol",
        search_lit.search_protocol,
        name="search_protocol",
    ),

    # --------------- searchs views urls ---------------
    path("<int:id>/run_search", search_lit.run_search, name="run_search"),

    # --------------- keywords views urls ---------------
    path("<int:id>/keyword", keywords.keyword, name="keyword"),

    # --------------- articles views urls ---------------
    path(
        "<int:id>/article_review/<int:article_id>",
        articles.article_review_detail,
        name="article_review_detail",
    ),
    path(
        "<int:id>/article_state_change",
        articles.article_state_change,
        name="article_state_change",
    ),
    path(
        "<int:id>/articles/",
        articles.article_reviews_list,
        name="article_reviews_list",
    ),
    path(
        "<int:id>/citation_updater/", 
        articles.citation_updater, 
        name="citation_updater"
    ),
    path(
        "<int:id>/article_tags/", 
        articles.article_tags, 
        name="article_tags"
    ),
    path(
        "<int:id>/duplicates_articles/",
        articles.duplicates_articles,
        name="duplicates_list_url",
    ),
    path(
        "<int:id>/review_article_full_text_pdf/<int:review_id>/",
        articles.review_article_full_text_pdf,
        name="review_article_full_text_pdf",
    ),

    # --------------- search_dash views urls ---------------
    path(
        "<int:id>/search_dashboard",
        search_dash.search_dashboard,
        name="search_dashboard",
    ),
    path(
        "<int:id>/search_terms/", citeviews.search_terms, name="search_terms"
    ),
    
    # --------------- ReportBuilder dash urls ---------------
    path(
        "<int:id>/report_builder",
        report_builder_dash.report_builder,
        name="report_builder",
    ),
    path(
        "<int:id>/exclusion_reason/",
        exclusion_reason.exclusion_reason_list_create,
        name="exclusion_reason",
    ),
    path(
        "<int:id>/exclusion_reason/<int:instance_id>/",
        exclusion_reason.exclusion_reason_update,
        name="exclusion_reason_update",
    ),
    path(
        "<int:id>/exclusion_reason/<int:instance_id>/delete/",
        exclusion_reason.exclusion_reason_delete,
        name="exclusion_reason_delete",
    ),

    # --------------- adverse_events urls ---------------
    path("<int:id>/adverse_database_summary/",
        adverse_events.adverse_database_summary,
        name="adverse_database_summary"
    ),
    path("<int:id>/manual_ae_searches/",
        adverse_events.manual_ae_searches,
        name="manual_ae_searches"
    ),
    path("<int:id>/delete_adverse_event/<int:ae_id>/",
        adverse_events.delete_adverse_event,
        name="delete_adverse_event"
    ),
    path("<int:id>/delete_adverse_recall/<int:ar_id>/",
        adverse_events.delete_adverse_recall,
        name="delete_adverse_recall"
    ),
    path("<int:id>/update_adverse_event/<int:ae_id>/",
        adverse_events.update_adverse_event,
        name="update_adverse_event"
    ),
    path("<int:id>/update_adverse_recall/<int:ar_id>/",
        adverse_events.update_adverse_recall,
        name="update_adverse_recall"
    ),
    path(
        "<int:id>/adverse_event_review/<int:ae_id>",
        adverse_events.adverse_event_review_detail,
        name="adverse_event_review_detail",
    ),
    path("<int:id>/adverse_events", adverse_events.ae_list, name="ae_list"),
    path(
        "adverse_event_review_single/",
        adverse_events.include_single_ae_review,
        name="single_ae_review",
    ),

    # --------------- product urls ---------------
    path("<int:id>/product_details", product.product_details, name="product_details"),
    path(
        "create_literaturereview",
        product.create_literaturereview,
        name="create_literaturereview",
    ),
    # --------------- clinical literature appraisals urls ---------------
    path(
        "<int:id>/clinical_literature_appraisals",
        cl_appraisal.clinical_appraisals_list,
        name="clinical_literature_appraisal_list",
    ),
    path(
        "<int:id>/clinical_literature_appraisal/<int:appraisal_id>",
        cl_appraisal.clinical_literature_appraisal,
        name="clinical_literature_appraisal",
    ),
    path('api/', include('lit_reviews.api.urls')),
    
    # --------------- full text uplode urls ---------------
    # path("upload_ft", ftviews.upload_ft, name="upload_ft"),
    path("<int:id>/full_text_upload", ftviews.ft_uploader, name="full_text_upload"),
    # path("<int:id>/full_text_clear/<int:article_review_id>/", ftviews.ft_clear, name="full_text_clear"),
    path(
        "<int:id>/ft_download_all_files",
        ftviews.ft_download_all_files,
        name="ft_download_all_files",
    ),
    path("fulltext_upload_help", ftviews.fulltext_upload_help, name="fulltext_upload_help"),
    # path("<int:id>/pdf_highlighter", ftviews.pdf_highlighter, name="pdf_highlighter"),
    

    # --------------- Extraction Fields urls ---------------
    path("<int:id>/extraction_fields", extraction_fields.home, name="extraction_fields"),


    ######################################
    ########## Search Notebook ##########
    ######################################
    # --------------- Search Notebook urls ---------------
    path("search_notebook/", search_notebook_views.home, name="search_notebook"),

]

admin_side/models.py
from django.db import models

# Create your models here.

admin_side/api/scraper_monitor/views.py
from rest_framework.generics import ListAPIView
from rest_framework import permissions, response, filters

from lit_reviews.models import ScraperReport, LiteratureReview, NCBIDatabase
from lit_reviews.api.cutom_permissions import isStaffUser
from lit_reviews.api.pagination import CustomPagination
from .serializers import (
    ScraperReportSerializer, 
    NCBIDatabaseSerializer,
    LiterateReviewSerializer,
)


class ScraperReportsListAPIView(ListAPIView):
    permission_classes = [
        permissions.IsAuthenticated,
        isStaffUser,
    ]
    serializer_class = ScraperReportSerializer
    pagination_class = CustomPagination
    queryset = ScraperReport.objects.all()
    # Explicitly specify which fields the API may be ordered against
    # ordering_fields = ('article__title', '-article__title', 'score', "-score")
    # This will be used as the default ordering
    ordering = ('id')
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['user__username', 'search_term']

    def apply_custom_filters(self, queryset):
        db_filter = self.request.query_params.get("database_name")
        review_filter = self.request.query_params.get("literature_review")
        status_filter = self.request.query_params.get("status")

        if db_filter:
            db_filter = db_filter.split(",")
            queryset = queryset.filter(database_name__in=db_filter)

        if review_filter:
            review_filter = review_filter.split(",")
            queryset = queryset.filter(literature_review__id__in=review_filter)

        if status_filter:
            status_filter = status_filter.split(",")
            queryset = queryset.filter(status__in=status_filter)

        return queryset 
    
    def get(self, request, *args, **kwargs):
        queryset = self.apply_custom_filters(self.get_queryset())
        queryset = self.filter_queryset(queryset)
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            res = self.get_paginated_response(serializer.data)
            reports = res.data
        else:
            serializer = self.get_serializer(queryset, many=True)
            reports = serializer.data 

        # Get list of reviews
        lit_reviews = LiteratureReview.objects.all()
        reviews_ser = LiterateReviewSerializer(lit_reviews, many=True)

        # Get list of databases
        dbs = NCBIDatabase.objects.all()
        dbs_ser = NCBIDatabaseSerializer(dbs, many=True)  

        return response.Response({
            "reports": reports,
            "dbs": dbs_ser.data,
            "lit_reviews": reviews_ser.data,
        })

    

admin_side/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import PermissionDenied

# Create your views here.
def home(request):
    if request.user.is_staff:
        return render(request, "admin_side/home.html") 
    else:
        raise PermissionDenied

templates/admin_side/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block 'title' %}{% endblock %}</title>
    {% block 'beforehead' %} {% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <link href="{% static 'css/theme/help_popup.css' %}" rel="stylesheet" type="text/css" />

    <!-- New Theme -->
    <link href="{% static 'css/theme/global.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/theme/layout.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/theme/lit_review_base.css' %}" rel="stylesheet" type="text/css" />
    {% block 'head' %} {% endblock %}
  </head>

  <body>
    <!-- NavBar -->
    <nav class="top-nav-bar" id="nav-bar">
      {% if review_title %}
      <div class="top-nav-bar-left-section">
        <div class="top-nav-bar-element">
          <div class="nav-bar-project-details">
            <div class="icon-section">
              <img src="{% static 'images/navbar/project icon.svg' %}" alt="project icon" />
            </div>
            
            <div class="text-section">
              <div class="upper"> {{project_details.project_name}} {{project_details.device_name}} </div>
              <div class="bottom"> {{ project_details.client_name }} </div>
            </div>
          </div>

          <div id="project-details-list-parent">
            <drop-down
              icon-source="{% static 'images/navbar/setting.svg' %}"
              target-element="project-details-list"
              parent-wrapper="project-details-list-parent"
              position-right="0px"
              position-top="35px"
            >
            </drop-down>
            <div class="drop-down" id="project-details-list">
              <ul>
                <li class="drop-down-element"> 
                  <div class="drop-down-element-icon">
                    <img src="{% static 'images/navbar/pen-edit.svg' %}" alt="Details Icon" />
                  </div> 
                  <a href="{% url 'literature_reviews:literature_review_detail' id=literature_review_id %}" class="drop-down-element-text">
                    Project Details
                  </a> 
                </li>
                <li class="drop-down-element"> 
                  <div class="drop-down-element-icon">
                    <img src="{% static 'images/navbar/pen.svg' %}" alt="Details Icon" />
                  </div> 
                  <a href="{% url 'literature_reviews:product_details' id=literature_review_id %}" class="drop-down-element-text">
                    Edit Project
                  </a> 
                </li>
              </ul>
            </div>
          </div>

        </div>
        
        <div class="vertical-devider"></div>
        <div class="app-version-section">
          <h3 class="app-version">Version {{app_version}}</h3>
          <a class="app-release" href="{{realease_notes_link}}" target="_blank">Read Release Note</a>
        </div>
        <div class="vertical-devider"></div>

        {% if env != 'PROD' %}
        <span style="color: red;"> TEST ENVIRONMENT </span>
        {% endif %}
     
      </div>
    
      <div class="top-nav-bar-right-section">
        <div class="vertical-devider"></div>

        <page-switcher
          first-page-label="Dashboard"
          second-page-label="Review"
          first-page-link="{% url 'client_portal:client_home' %}"
          second-page-link="{% url 'literature_reviews:literature_review_list' %}"
          active-page="Review"
          type="DASHBOARD"
        >
        </page-switcher>

      </div>
      {% endif %}
    
    </nav>
    <!-- NavBar END -->


    <div>
      <!-- Sidebar -->
      <div class="sidebar" id="side-bar">
        <!-- Logo -->
        <div class="logo-section">
          <a
            class="logo-icon {% if not review_title %} mr-auto {% endif %}"
            href="{% url 'literature_reviews:literature_review_list' %}"
          >
            <img
              src="{% static 'images/new_logo.svg' %}"
              height="30"
              class="d-inline-block align-top"
              alt="citemed logo"
            />
          </a>
        </div>
        {% include "admin_side/side_bar.html" %}
      </div>
      <!-- sidebar-container END -->

      <!-- MAIN -->
        {% if not hide_body_conent %}
          <div class="body-content">
        {% endif %}      
        
          {% block 'body' %} {% endblock %}
      
        {% if not hide_body_conent %}
          </div>
        {% endif %} 
        
        <!-- Support Help Center -->
        {% comment %} {% if literature_review_id != 'Unknown' %} {% endcomment %}
          <!-- Show only inside project details pages -->
          <div id="app-lit-review" style="position: absolute;">
            <div class="help-popup hide" id="help-popup">
              <div>
                <div class="help-popup-header">
                  <div class="title">
                    Help Center
                  </div>
                  
                </div>
                
                <div id="request-help" class="help-popup-content">

                  <div class="request-help-btns">                                                                              
                    <div class="help-btn-link">
                      {% block 'help_section' %} {% endblock %}
                    </div>

                    <div class="help-btn-link" v-on:click="()=> onRequestHelp('SUPPORT_CALL','{{ request.get_full_path }}')">
                      <a href="javascript:void(0);">
                          <span>Book ScreenShare Support Call</span>
                          <div>
                            <img src="{% static 'images/icons/video-icon.svg' %}">
                          </div>
                      </a>
                    </div>                  
                  </div>

                  <div class="horizantal-devider"> </div>

                  <form id="form-request"  class="form help-form " method="post">
                    <div class="form-title"> Or Submit a Support Request Form </div>
                    <div>
                      <label for="message">How can we help?</label>
                      <textarea name="message" id="message" cols="30" rows="3" class="textarea" v-model="message"></textarea>
                    </div>
                    <div>
                      <label for="demo_video">Show us the issue (Send a <span style="text-decoration: underline;color: #6D6BAF;">Loom Video</span>)</label>
                      <textarea name="demo_video" id="demo_video" cols="30" rows="3" v-model="demo_video"></textarea>
                    </div>

                    <div class="">
                      <label>How do you want us to follow-up?</label>
                      <div class="follow-up">
                      <div>
                        <label class="" for="call_me">
                          <input class="mr" id="call_me" type="checkbox" v-model="help_channels" value="CALL">
                          <span class="ml">  
                            Call Me
                          </span>
                        </label>
                      </div>
                      <div>
                        <label for="email">
                          <input class="form-check-input" id="email" type="checkbox" v-model="help_channels" value="EMAIL">
                          <span class="ml">  
                            Email
                          </span>
                        </label>
                      </div>
                      <div>
                        <label for="teams_meeting">
                          <input class="form-check-input" id="teams_meeting" type="checkbox" v-model="help_channels" value="MEETING">
                          <span class="ml">  
                            Teams Meeting
                          </span>
                        </label>
                      </div>
                    </div>
                    </div>
                    <input 
                      type="button" 
                      name="save" 
                      value="Submit Form" 
                      v-on:click="()=> onRequestHelp('SUPPORT_TICKET', '{{ request.get_full_path }}')" 
                      class="primary-button mt-3"
                      style="margin-left: auto;"
                      :disabled="isSubmit"
                    />
                  </form>                  
                </div>

                
                  
                  <div class="sucess-submit hide " id="success-submit">
                  <div class="form-title"> Or Submit a Support Request Form </div>
                  <div>
                     <div class="success-submit-text">Your request has been submitted,</div>
                     <div class="message-content">we will get back to you as soon as possible with a helpful reply!</div> 
                  </div>
                  <img src="{% static 'images/bro.svg' %}" style="width: 75%;" >
                  {% comment %} <div class="actions">
                    <button class="secondary-gray-button" v-on:click="onReturnForm">
                      Return
                    </button>
                    <button class="primary-button" v-on:click="showPopup">
                      Close
                    </button>
                  </div> {% endcomment %}
                </div>
              </div>
            </div>

         
          <div @mousedown="onMousedown" class="help-popup-btn" id="popup-btn" v-on:click="showPopup">
            <div v-if="isshowPopup" class="help-btn-close">
              <img src="{% static 'images/icons/close-x-icon.svg' %}">
            </div>
            <img v-else src="{% static 'images/icons/popup.svg' %}">
          </div>
            
          </div>
        {% comment %} {% endif %} {% endcomment %}
      </div>    
      <!-- Main Col END -->
    </div>
    <!-- body-row END -->

   </body>

  

<script type="application/javascript" src="{% static 'lit_reviews/js/globe.js' %}"></script>
{% if env == 'PROD' %}
<script type="application/javascript" src="https://cdn.jsdelivr.net/npm/vue@2.7.0"></script>
{% else %}
<script type="application/javascript" src="https://cdn.jsdelivr.net/npm/vue@2.7.0/dist/vue.js"></script>
{% endif %}

<script type="application/javascript" src="https://cdn.jsdelivr.net/npm/portal-vue@2.1.7/dist/portal-vue.umd.min.js"></script>
<script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js" integrity="sha512-odNmoc1XJy5x1TMVMdC7EMs3IVdItLPlCeL5vSUPN2llYKMJ2eByTTAIiiuqLg+GdNr9hF6z81p27DArRFKT7A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="application/javascript" src="{% static 'lit_reviews/vue/mixins.js' %}" > </script>
<script type="application/javascript" src="{% static 'lit_reviews/vue/components/ui_elements.js' %}" > </script>
<script type="application/javascript" src="{% static 'lit_reviews/vue/navbar.js' %}" > </script>
<script type="application/javascript" src="{% static 'lit_reviews/vue/sidebar.js' %}" > </script>
<script type="application/javascript" src="{% static 'lit_reviews/vue/help_popup.js' %}"></script>

{% block 'after-body' %} {% endblock %}
{% block 'scripts-block' %} {% endblock %}

</html>

templates/admin_side/side_bar.html
{% load static %} 



<div class="sidebar-content">
  <ul class="menu-list sidebar-menu-container">
    <!-- <li>
      <div class="switcher-container">
        <div class="toggle-wrapper"> 
          <span class="text" id="toggle-label" style="cursor: pointer;"> Simple / Advanced Mode </span>
          <div class="toggle" id="toggle">
            <div class="toggle-ball" id="toggle-ball"></div>
          </div>
        </div>
      </div>
    </li> -->
 

    <li class="">
     
        <h2 style="text-align: center;"> Admin Panel </h2>       
    </li>

  </ul>

  <div class="user-navigation">
    <div class="text user-name-email-section">
      <div>{{ request.user.username }}</div>
      <div>{{ request.user.email }}</div>
    </div>

    <div id="user-navigation-parent">
      <drop-down
        icon-source="{% static 'images/navbar/setting.svg' %}"
        target-element="user-navigation-list"
        parent-wrapper="user-navigation-parent"
        position-right="20px"
        position-bottom="40px"
      >
      </drop-down>
      <div class="drop-down" id="user-navigation-list">
        <ul>
          {% if request.user.is_staff %}
            <li class="drop-down-element">
             <div class="drop-down-element-icon">
                <img
                  src="{% static 'images/navbar/lock.svg' %}"
                  alt="Details Icon"
                />
              </div>
              <a
                href="{% url 'admin_side:admin-side-home' %}"
                class="drop-down-element-text"
              >
                Admin Panel
              </a>
            </li>
          {% endif %}
          <li class="drop-down-element">
            <div class="drop-down-element-icon">
              <img
                src="{% static 'images/navbar/pen-edit.svg' %}"
                alt="Details Icon"
              />
            </div>
            <a
              href="{% url 'accounts:logout' %}"
              class="drop-down-element-text"
            >
              Logout
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>